receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu:
      memory:
      load:

processors:
  batch:
  attributes/remove_client_address:
    actions:
      - key: client.address
        action: delete

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  debug:
    verbosity: detailed  	  

extensions:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, attributes/remove_client_address]
      exporters: [otlp]
    metrics:
      receivers: [hostmetrics, otlp]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]	
  extensions: [zpages]